project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right: 
      - icon: github
        menu:
          - text: Website Source Code
            url:  https://github.com/abellula/personal-website
          - text: Github Profile
            url:  https://github.com/abellula
  page-footer:
    right: "&copy; 2024, Abel Lula"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
